### PR TITLE
style: fix incorrect switcher width on small screen sizes

### LINKED ISSUE #994: (SP: 0.5) Incorrect width of the currency switcher on the Support Us page on the small screens
## Summary

Currency switcher does not stretch to full screen width on mobile, unlike the design.

## Severity

- [ ] Blocker
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

## Expected behavior

Switcher should occupy full width of the viewport on mobile

## Actual behavior

Switcher is rendered with reduced width and does not stretch to the screen edges

## Screenshots

Image

Image

### PR DESCRIPTION
**Pull request by Taras-ep**
## Description

Incorrect switcher width on mobile devices. It must be full-width on mobile screens instead of having a fixed width.

## Type of change

- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring / Tech debt
- [ ] CI/CD improvement
- [ ] Other: 

## Video / Screenshots

# Before
image
image

# After
image
image

## Checklist

- [x] PR name follows the naming convention
- [x] Code compiles and runs correctly
- [x] Tests pass successfully
- [x] Linting checks are clean
- [x] No Sonar issues
- [x] Documentation updated (if applicable)
- [x] All comments and requested changes addressed
- [x] Branch is up to date with the target branch
- [x] Linked issue/task included
- [x] Task moved to the review column on the board

### CODE REVIEW

File: app/shared/components/blocks/payment-details/PaymentDetails.tsx [hunk 1]
```diff
@@ -14,10 +14,25 @@ function PaymentDetails() {
...
+          xs: `calc((100% - 8px) / ${buttonsCount})`,
+          sm: '66px'
+        }
+      }
+    };
+  }, []);
+
   return (
-    <Box data-testid="PaymentDetails">
+    <Box sx={{ 'margin-right': '24px' }} data-testid="PaymentDetails">
```
Comment (qqwz0) [inline app/shared/components/blocks/payment-details/PaymentDetails.tsx]: maybe it would be more consistent to use the shorthand:`<Box sx={{ mr: '24px' }}>`

**Review by qqwz0 — APPROVED** [review]

File: app/shared/components/blocks/payment-details/PaymentDetails.tsx (hunk 1 above)
Comment (Taras-ep) [reply app/shared/components/blocks/payment-details/PaymentDetails.tsx]: Good catch, updated to 'mr' for consistency.

**Review by stsvt — APPROVED** [review]

**Review by bandvov — APPROVED** [review]
