### PR TITLE
fix(analytics): prevent tracking requests when consent is denied

### LINKED ISSUE #1194: [Bug][Coookie] Coookie collect request sent with gcs=G100 parameter if cookie_consent {"analytics":false}
## Steps to Reproduce

1. Open the app.
2. Open the cookie tab.
3. Click the Customize cookie button.
4. Cancel the permission to send analytics data and save settings.
5. Review the cookie tab and value for the cookie_consent name.
6. Press F5.
7. Review the result.

## Actual Result

Image

Image

## Expected Result

no request sent

### PR DESCRIPTION
**Pull request by Fedorieieva**
## Description

This PR fixes a bug where the application continued to send analytics requests (with the `gcs=G100` parameter) even when the user had explicitly denied analytics consent. The issue was caused by the `ConsentScript` initializing prematurely or incorrectly parsing the `analytics: false` state in the consent cookie.

**Key changes:**
* **Conditional Initialization:** Updated the logic to strictly check for the `analytics: true` value within the `cookie_consent` object.
* **Component Guard:** Modified the component to return `null` instead of rendering the `ConsentScript` if analytics consent is not granted.
* **Request Prevention:** Ensured that no Google Analytics or GTM scripts are injected into the DOM when consent is denied, effectively stopping the `collect` requests.
* **Test Synchronization:** Updated the test suite to verify the absence of tracking scripts in the document when the refusal state is active.

## Type of change

- [x] Bug fix

## How to test

1. Open the application and open the **Network** tab in DevTools.
2. Open the **Cookie Consent** banner/tab.
3. Click the **'Customize'** button.
4. Disable (toggle off) the **Analytics** permission and save the settings.
5. Check the `cookie_consent` value in the Application tab — it should show `{"analytics": false}`.
6. Press **F5** to reload the page.
7. **Verify the following:**
    * In the **Network** tab, there should be **no requests** to `google-analytics.com/g/collect`.
    * In the **Elements** tab, the Google Tag Manager and GA scripts should **not be present**.
    * The `gcs=G100` parameter (which indicates denied consent but initialized script) should no longer appear because the script is not loaded at all.

Closes [#1194](https://github.com/Liatoshynsky-Foundation/lf-client/issues/1194)

### CODE REVIEW

**Comment by DenisGordProgrammer** [comment]
Rename the PR according to our rules, please

**Review by DenisGordProgrammer — APPROVED** [review]

File: app/shared/components/cookie-modal/CookieModalWrapper.tsx [hunk 1]
```diff
@@ -16,12 +16,14 @@ const CookieModalWrapper = ({ trackingId, gtmId, consent_cookie }: ConsentProps)
   const [open, setOpen] = useState(true);
   const [openPreferences, setOpenPreferences] = useState(false);
   const [collectAnalytics, setCollectAnalytics] = useState(true);
-  const [analiticsEnabled, setAnaliticsEnabled] = useState(Boolean(consent_cookie));
-
+  const [analiticsEnabled, setAnaliticsEnabled] = useState(consent_cookie?.analytics ?? false);
```
Comment (Jevgan) [inline app/shared/components/cookie-modal/CookieModalWrapper.tsx]: Maybe it would be reasonable to alter `Analitics` to `Analytics` in order to prevent further confusion.

**Review by Jevgan — APPROVED** [review]
