### PR TITLE
fix: close dropdown menus on scroll down in header

### LINKED ISSUE #758: (SP: 0.5) UI: Dropdown menu in header stays on screen when scrolling
## Environment:
Windows 11
Chrome 141.0.7390.108
Firefox 144.0
Edge 141.0.3537.85

## Description:
When the user opens the dropdown menu in the header (Foundation → submenu or Borys Liatoshynskyi → submenu) and scrolls the page down without closing it, the menu becomes detached from the header and “floats” on the page.

## Steps to reproduce:

1. Go to the homepage or any page with the header.
2. Open the dropdown menu in the header (e.g. “Foundation”).
3. Without closing it, scroll the page down.

## Expected result:
The dropdown menu should either stay attached to the header or automatically close when scrolling.

## Actual result:
The menu stays visible and detached from the header, appearing as a floating element on the page.

https://github.com/user-attachments/assets/5162855c-550a-4737-a0a7-015a511ad1ee

### PR DESCRIPTION
**Pull request by alisa-korniienko**
## Description

Fixes dropdown menu behavior in header during scrolling.

## Type of change

- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring / Tech debt
- [ ] CI/CD improvement
- [ ] Other: 

## How to test

1. Run the project
2. Navigate to the homepage or any page with header
3. Open navigation dropdown ("Борис Лятошинський" or "Фундація" button)
4. Without closing the dropdown, scroll down the page
5. Verify that the dropdown automatically closes when scrolling down
6. Repeat steps 3-5 for the language switcher (globe icon)
7. Test other dropdowns on the site (filters, etc.) to ensure they still work as before

## Video / Screenshots

https://github.com/user-attachments/assets/817c0e16-bbd3-4977-bd7c-3f1f395c90a1

## Checklist

- [x] Code compiles and runs correctly
- [x] Tests pass successfully
- [x] Linting checks are clean
- [x] No Sonar issues
- [ ] Documentation updated (if applicable)
- [ ] All comments and requested changes addressed
- [x] Branch is up to date with the target branch
- [x] Linked issue/task included
- [x] Task moved to the review column on the board

---

### CODE REVIEW

File: app/shared/components/design-system/all-components/navigation-bar/NavigationBar.tsx [hunk 1]
```diff
@@ -7,10 +7,19 @@ import useBreakpoints from '~/hooks/use-breakpoints/useBreakpoints';
...
-const NavigationBar = ({ navLabels, specialNav }: { navLabels: NavigationDTO[]; specialNav: NavigationDTO | null }) => {
+const NavigationBar = ({
+  navLabels,
+  specialNav,
+  scrollDirection
+}: {
+  navLabels: NavigationDTO[];
+  specialNav: NavigationDTO | null;
+  scrollDirection: ScrollDirection;
+}) => {
```
Comment (stsvt) [inline app/shared/components/design-system/all-components/navigation-bar/NavigationBar.tsx]: It might make sense to extract the prop types into a separate interface

Comment (alisa-korniienko) [reply app/shared/components/design-system/all-components/navigation-bar/NavigationBar.tsx]: Good point! I'll extract the props into a separate interface for better readability and consistency with other components.

**Review by stsvt — APPROVED** [review]

**Review by Taras-ep — APPROVED** [review]

**Review by Kryzhanivsky — APPROVED** [review]

**Review by luvthenika — APPROVED** [review]
