### PR TITLE
(SP: 0.5) Fix bugs and implement improvements for issues #586, #584, and #595 related to search component

### LINKED ISSUE #584: (SP: 0.5) Bugfix: Incorrect color for search icon invisible during non-active and active states (white on white)
Image

Actual result:
The icon button is white without a black border line on a white background and not visible 
The search icon color is black
Expected result:
Non-active:  white outlined icon button with black stroked search and white fill
Active:  black filled icon button with white stroked search and black fill

### LINKED ISSUE #586: (SP: 0,5 )Bugfix: Search bar does not animate back into icon when clicking outside
**Summary**
When the search is opened it expands with an animation. Clicking outside should collapse it back into the icon with the reverse animation, but it remains visually expanded (no collapse animation).

**Repro steps**

Open the page with the search control.
Click the search icon (search expands with animation).
Click anywhere outside the search control.

**Actual**
Search stays expanded and active; SVG/icon does not animate back to its compact icon state.

**Expected**
Clicking outside triggers collapse animation and the control returns to the compact icon state (icon visible, active classes removed).

Image

### LINKED ISSUE #595: (SP: 0.5) Fix bugs related to the search component
## Description
Need to fix Sonar issues from previous PR. (https://github.com/Liatoshynsky-Foundation/lf-client/pull/527)

Image

Also found a bug with the search field:

https://github.com/user-attachments/assets/0d18cf54-f006-4052-a74d-9717bf2637c4

## Steps to Reproduce

1. Go to the page "Creativity of Lyatoshynsky".
2. Use search
3. Clear search query
4. Try using filters

## Actual Result

The search value is returned to the field and executed again.

## Expected Result

Filters open and do not change the state in the search field.

### PR DESCRIPTION
**Pull request by luvthenika**
## Description

Closes #586 
Closes #584 
Closes #595 
## Type of change

- [ ] New feature
- [x] Bug fix
- [ ] Documentation update
- [ ] Refactoring / Tech debt
- [ ] CI/CD improvement
- [ ] Other: 

## What was done

1. Fixed icon button styling properties for correct color of the search icon
2. Fixed 2 sonar issues by extracting complex conditions into separate helper functions and removed nested ternary strings
3. Updated Zod validation errora along the way
4. Addressed issue with Search Bar component , by regulating closing logic during blur and disabling list when user click outside the component

## Video / Screenshots

https://github.com/user-attachments/assets/5870ab52-fbdc-4a56-ac88-f7f9b874b6b2

## Checklist

- [x] Code compiles and runs correctly
- [x] Tests pass successfully
- [x] Linting checks are clean
- [ ] No Sonar issues
- [ ] Documentation updated (if applicable)
- [ ] All comments and requested changes addressed
- [x] Branch is up to date with the target branch
- [x] Linked issue/task included
- [x] Task moved to the review column on the board

---

### CODE REVIEW

**Comment by luvthenika** [comment]
i need help with sonar issue detector as i have been  refactoring the same code more than twice and it still marks issue
i need team's help

**Review by Kryzhanivsky — CHANGES_REQUESTED** [review]
Please fix the places with type "any". And try to avoid this in the future, it creates problems in development.

File: app/lib/utils/searchAndFiltersHelpers.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import { escapeRegex } from './escapeRegex';
+
+export const searchHelper = (search?: string) => {
+  if (!search) return '';
```
Comment (ssashayurchenko) [inline app/lib/utils/searchAndFiltersHelpers.ts]: maybe it will be better to return null for example instead of empty string? since we return an array in the end
```suggestion
  if (!search) return null;
```

Comment (luvthenika) [reply app/lib/utils/searchAndFiltersHelpers.ts]: empty string is coerced in the if statement , so if there is no serach statement in wont run in both ways , but i agree with the semantic clarity, good catch

File: app/shared/components/enhanced-table/control-panel/ControlPanel.styles.ts [hunk 2]
```diff
@@ -1,3 +1,5 @@
+import { mainHexPallete } from '~/ds-components//theme/colors';
+
 export const ControlPanelStyles = {
   root: (theme: any) => ({
```
Comment (Kryzhanivsky) [inline app/shared/components/enhanced-table/control-panel/ControlPanel.styles.ts]:
```suggestion
  root: (theme: Theme) => ({ //Theme from Mui material
```

**Review by Kryzhanivsky — CHANGES_REQUESTED** [review]

**Review by Kryzhanivsky — APPROVED** [review]

**Review by Iarynovskyi — APPROVED** [review]

**Review by ssashayurchenko — APPROVED** [review]
