### PR TITLE
Fix CookieModalWrapper any type

### LINKED ISSUE #712: (SP: 0.5) Fix CookieModalWrapper any type
## Steps to Reproduce

1. Run lint
2. Open CookieModalWrapper.tsx

## Actual Result

Image

## Expected Result

No Warning

### PR DESCRIPTION
**Pull request by alisa-korniienko**
## Description

Remove the `any` type in `CookieModalWrapper.tsx` and add type-safe overloads for `window.gtag` based on real usage.

## Type of change

- [x] Bug fix  
- [ ] New feature  
- [ ] Documentation update  
- [ ] Refactoring / Tech debt  
- [ ] CI/CD improvement  
- [ ] Other: 

## How to test

1. Run ESLint on the modified file:
   npm exec eslint app/shared/components/cookie-modal/CookieModalWrapper.tsx
No warnings should appear.

2. Verify that the cookie modal works correctly on TEST environment — open the main page and confirm that the cookie consent logic still works (“Accept all” and “Configure” actions).

## Checklist

- [x] Code compiles and runs correctly
- [x] Tests pass successfully
- [x] Linting checks are clean
- [x] No Sonar issues
- [x] Documentation updated (if applicable)
- [x] All comments and requested changes addressed
- [x] Branch is up to date with the target branch
- [x] Linked issue/task included
- [x] Task moved to the review column on the board

---

**Linked issue:** #712  
**Story Point:** (SP: 0.5)

### CODE REVIEW

File: app/shared/components/cookie-modal/CookieModalWrapper.tsx [hunk 1]
```diff
@@ -4,11 +4,16 @@ import React, { useState } from 'react';
...
+import type { parseDaConsent } from '~/lib/utils/consent';
 import { consentObj } from '~/lib/utils/consent';
 
 declare global {
   interface Window {
-    gtag: (...args: any[]) => void;
+    gtag: {
+      (command: 'consent', action: 'update', params: ReturnType<typeof consentObj>): void;
+
+      (command: 'consent', action: 'default', params: ReturnType<typeof parseDaConsent>): void;
```
Comment (yur4uwe) [inline app/shared/components/cookie-modal/CookieModalWrapper.tsx]: I dunno, you can delete this type definition as its use only by runtime js and ts won't be able to catch calls there. If you don't want don't do it. But don't forget to resolve this conversation before merging (i know you won't)

Comment (alisa-korniienko) [reply app/shared/components/cookie-modal/CookieModalWrapper.tsx]: Hi @yur4uwe! Thanks for the review!

I've updated the code to simplify the type definition - removed the unnecessary parseDataConsent import and union type, now using just ReturnType<typeof consentObj>.

I'm a bit confused though - the task is literally "Fix any type", but you're suggesting to remove types entirely. I can totally do that if these types don't add real value or we can keep it for better autocompletion and clarity.

Quick question: should we maybe wait for another reviewer's opinion? Or I can just go with your suggestion and remove it - whatever works best for the team!

Let me know!

Comment (yur4uwe) [reply app/shared/components/cookie-modal/CookieModalWrapper.tsx]: I meant only one with `parseDaConsent` as its only executed on runtime. There is no reason to overload type definition as the only time WE really call `gtag` is at the consent update. Therefore your current definition is perfect for us. And the removal of `ReturnType<parseDaConsent>` is a nice touch. It was only created for parsing consent object to string to insert it correctly at default consent call.

**Review by yur4uwe — APPROVED** [review]

File: app/shared/components/cookie-modal/CookieModalWrapper.tsx (hunk 1 above)
Comment (alisa-korniienko) [reply app/shared/components/cookie-modal/CookieModalWrapper.tsx]: Thanks for the clarification and approval!
I understand now - keeping it simple with just `ReturnType<typeof consentObj>` makes sense!

Comment (yur4uwe) [reply app/shared/components/cookie-modal/CookieModalWrapper.tsx]: https://github.com/user-attachments/assets/0dd153b2-a58a-4761-98d1-ef6ee1e819c4

**Review by Kryzhanivsky — APPROVED** [review]

**Review by VKormylo — APPROVED** [review]

**Review by Taras-ep — APPROVED** [review]
