### PR TITLE
Fix(ui): unify clear filter button styles and extract into reusable component

### LINKED ISSUE #804: (SP: 0.5) Unify clear button styles in filter dropdowns
## Description

Clear buttons inside filter dropdowns currently have different appearance. We need to unify their style to match the design system clear button style.

## Expected Result

All clear/reset buttons in filter dropdowns look and behave the same across the app.

## Extra

Figma design vs clear button on Category and Genre

Image

Image

### PR DESCRIPTION
**Pull request by qqwz0**
## Description

Unified the Clear button styling across filter components and extracted it into a reusable ClearFilterButton component.  

## Type of change

- [x] Bug fix

## How to test

1. Open any table with filters (e.g., composition table).
2. Open genre / category filter dropdown and verify clear button matches design system and numeric clear button.
3. Open numeric filter and verify clear button matches design system.

## Video / Screenshots

https://github.com/user-attachments/assets/7d925b1b-778d-40fb-ac10-40959bc9398b

## Checklist

- [x] Code compiles and runs correctly
- [x] Tests pass successfully
- [x] Linting checks are clean
- [x] No Sonar issues
- [ ] Documentation updated (if applicable)
- [ ] All comments and requested changes addressed
- [x] Branch is up to date with the target branch
- [x] Linked issue/task included
- [x] Task moved to the review column on the board

---

### CODE REVIEW

**Review by Kryzhanivsky — APPROVED** [review]
Approved, but can you fix these paddings and the difference in colors (the contrast in the image is increased)?
Знімок екрана 2025-10-31 141341

**Comment by qqwz0** [comment]
> Approved, but can you fix these paddings and the difference in colors (the contrast in the image is increased)? Знімок екрана 2025-10-31 141341

i partially fixed it in https://github.com/Liatoshynsky-Foundation/lf-client/pull/759 (removed side paddings). do you mind if i fix it there?

**Review by Kryzhanivsky — APPROVED** [review]
Okay, then I'll close the comment here, but open it on another PR. It's better to complete this task there.

File: app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.tsx [hunk 1]
```diff
@@ -1,18 +1,15 @@
...
 import { useTranslations } from 'next-intl';
 import { useCallback, useEffect, useMemo, useState } from 'react';
 
-import { Svg } from '~/components/colored-svg/ColoredSvg';
-import Button from '~/ds-components/button/Button';
 import { DesignSystemSlider } from '~/ds-components/slider/Slider';
 import TextField from '~/ds-components/text-field/TextField';
-import { mainHexPallete, rgbaClearFilterButton } from '~/ds-components/theme/colors';
 
+import ClearFilterButton from '../../clear-filter-button/ClearFilterButton';
```
Comment (NatalyKrvch) [inline app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.tsx]: approve, but fix import here please

**Review by NatalyKrvch — APPROVED** [review]

**Review by bandvov — APPROVED** [review]

File: app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.tsx (hunk 1 above)
Comment (qqwz0) [reply app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.tsx]: done!
