### PR TITLE
Fix update GetNotes modals text and responsive layout

### LINKED ISSUE #736: (SP: 1) Fix: Update text in GetNotes modal to be responsive and match Figma
## Description

The confirmation modal within the GetNotes flow currently does not fully match the Figma design. The displayed text differs from the expected copy, and on smaller screens the modal layout (especially padding and max-width) causes layout inconsistencies — e.g., text wrapping unexpectedly, overflow issues, and uneven spacing.

## Steps to reproduce

1. Navigate to  /artistry -> Переглянути ноти. 
2. Click Переглянути ноти
3. Proceed to Зв'язатись з нами and Надіслати запит
4. Compare modals layout and text with the Figma reference
5. Resize the window to simulate small and medium breakpoints (≤768px)

## Expected Result

The confirmation modal text exactly matches the Figma copy.
All GetNotes modals remain visually consistent across responsive breakpoints.
No overflow; wraps naturally and is readable on small screens.

## Extra
The example of current implementation vs Figma
Image

Image

### PR DESCRIPTION
**Pull request by qqwz0**
## Description

This PR updates all GetNotes modals (List, Form, and Confirmation) to ensure full consistency with the Figma design and correct responsive behavior across breakpoints.

## Type of change

- [x] Bug fix

## How to test

1. Navigate to /artistry → Переглянути ноти → Зв'язатись з нами → Надіслати запит.
2. Compare the modals text with the Figma copy.
3. Resize the viewport to different screen widths and check that the text wraps naturally and the modal layout remains consistent.

## Video / Screenshots

https://github.com/user-attachments/assets/c4f60ec3-b552-4ff5-bf72-8bddfce3536c

## Checklist

- [x] Code compiles and runs correctly
- [x] Tests pass successfully
- [x] Linting checks are clean
- [x] No Sonar issues
- [ ] Documentation updated (if applicable)
- [ ] All comments and requested changes addressed
- [ ] Branch is up to date with the target branch
- [x] Linked issue/task included
- [x] Task moved to the review column on the board

---

### CODE REVIEW

**Review by oleg191006 — APPROVED** [review]

**Review by bandvov — APPROVED** [review]

**Review by oleg191006 — APPROVED** [review]

**Review by alisa-korniienko — APPROVED** [review]

File: app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListItem.tsx [hunk 1]
```diff
@@ -17,32 +19,44 @@ type NotesListItemProps = {
...
     </Button>
   );
 
+  const buttonWithLink = note.isFree ? (
+    <a href={note.url} target="_blank" rel="noopener noreferrer">
+      {button}
+    </a>
+  ) : (
+    button
+  );
```
Comment (yur4uwe) [inline app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListItem.tsx:48]: The custom `Button` already supports links but only on the same site, i think it would be wise to instead extend Button component with something like a flag parameter `sameSite` or `blankTarget` that is responsible for using other type of `Link` as `Link` component used now is next-intl component and isn't equipped for such trasks

Comment (qqwz0) [reply app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListItem.tsx:48]: good point. should I create a separate task for it?

Comment (yur4uwe) [reply app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListItem.tsx:48]: No need, do it in this pr, just make sure nothing breaks and also update button mock

**Review by yur4uwe — APPROVED** [review]
