### PR TITLE
Middleware meddling with icon imports fix 

### LINKED ISSUE #84: Middleware changing request path meddling with icon imports
## Reproducible when

always

## Reproducible by

Opening site's page

## Description

When opening site icons do not load

Appearence:

Image

Browser console errors:

Image

 ## Possible cause

As described in error, site cannot find [lang]/[icon name].svg icon, this is most possible caused by locale adding middleware changing requests for static resources

### LINKED ISSUE #114: Small middleware matcher Regex error
## Current Regex:

\/((?!api|_next\/static|_next\/image|favicon.ico|.\*\\.[^\/]+$).*)

## Visualization:

Image

## Description

Because '.' character between favicon and ico isn't treated as character by Regex, but as control character which means "any character", its possible to create strange paths that wont go through middleware like /favicon#ico. This is not severe as only one character can be inbetween favicon and ico, but issue nonetheless

### PR DESCRIPTION
**Pull request by yur4uwe**
## Summary of issue

Solution for bug #84. 

## Summary of change

Solves issue by changing middleware matcher Regex for Next config. New regex additionaly matches all paths which have '.' and at least 1 non-slash character after, up to the end of the string

### Before fix

image

### After fix

image

### CODE REVIEW

**Comment by Iarynovskyi** [comment]
https://github.com/user-attachments/assets/54029add-7d97-4ca2-ba64-3b88ada96d24

**Comment by yur4uwe** [comment]
> 2025-05-24.18.44.19.mov

I see the issue

**Comment by Iarynovskyi** [comment]
> > 2025-05-24.18.44.19.mov
> 
> Is this footage before or after applying my changes?

After. I yesterday looked on this bug so know where to check it

app/components/Footer/FooterCopyrights/FooterCopyrights.styles.ts

In this file change icon import to this one    ->    backgroundImage: 'url(/Bullet-icon.svg)',
Without ' . ' and than it should work correct

**Comment by yur4uwe** [comment]
> > > 2025-05-24.18.44.19.mov
> > 
> > 
> > Is this footage before or after applying my changes?
> 
> After. I yesterday looked on this bug so know where to check it
> 
> app/components/Footer/FooterCopyrights/FooterCopyrights.styles.ts
> 
> In this file change icon import to this one -> backgroundImage: 'url(/Bullet-icon.svg)', Without ' . ' and than it should work correct

Its sure isnt the case because i use next Image component for another icon component with /copy-icon.svg, and it still fails to fetch it

**Comment by yur4uwe** [comment]
image

here is without isIcon function

**Comment by Iarynovskyi** [comment]
> image
> 
> here is without isIcon function

Well, I just checked the icons that are shown in bug here and with your function and removing ' . ' it was fixed, but if your icon in your PR does not work, then the problem is deeper..

**Comment by yur4uwe** [comment]
> > image
> > here is without isIcon function
> 
> Well, I just checked the icons that are shown in bug here and with your function and removing ' . ' it was fixed, but if your icon in your PR does not work, then the problem is deeper..

Well, that why i created this pr after all

**Comment by bandvov** [comment]
> > > image
> > > here is without isIcon function
> > 
> > 
> > Well, I just checked the icons that are shown in bug here and with your function and removing ' . ' it was fixed, but if your icon in your PR does not work, then the problem is deeper..
> 
> Well, that why i created this pr after all

Lets first merge PR with i18n setup(#83 ). After that you should check if problem is solved

**Review by ShadowOfTheSpace — COMMENTED** [review]
Can you enhance the `matcher` of the middleware instead of all this extra logic?

**Comment by Iarynovskyi** [comment]
> Can you enhance the `matcher` of the middleware instead of all this extra logic?

The middleware `matcher` does not apply to files in the` public/` folder
They are served statically and bypass middleware
So i think we need extra logic for handling those cases

**Comment by yur4uwe** [comment]
> Can you enhance the `matcher` of the middleware instead of all this extra logic?

For sure, the only reason i added this custom logic comes from personal preferences and lacking understanding of regex

**Comment by yur4uwe** [comment]
> The middleware `matcher` does not apply to files in the` public/` folder They are served statically and bypass middleware So i think we need extra logic for handling those cases

` public/` folder do get through middleware though, thats why this bug exists in the first place

**Comment by yur4uwe** [comment]
> Can you enhance the `matcher` of the middleware instead of all this extra logic?

I sure can, its just a matter of my taste to add string manipulation, as i understand it better, but i see the reason for them to be added

**Comment by ShadowOfTheSpace** [comment]
> > Can you enhance the `matcher` of the middleware instead of all this extra logic?
> 
> The middleware `matcher` does not apply to files in the` public/` folder They are served statically and bypass middleware So i think we need extra logic for handling those cases

Probably you have problems with `matcher`. Please, check on which routes `middleware` invokes. Just add console.log to the `req.nextUrl` or smth like that inside body of the middleware (middleware.ts file). If there are routes that should be ignored by the matcher - something is wrong.
Also, check [this article on the Nextjs docs](https://nextjs.org/docs/app/building-your-application/routing/middleware#matching-paths), middleware invokes on every route (it doesn't matter whether the route is static or not).

Also in the `next-intl` lib, I saw that they are [proposing](https://next-intl.dev/docs/getting-started/app-router/with-i18n-routing#middleware) to include `.*\\..*` into the matcher (it will exclude all URLs that look like files, for example - static files). It might help with this issue.

**Comment by ShadowOfTheSpace** [comment]
> > Can you enhance the `matcher` of the middleware instead of all this extra logic?
> 
> I sure can, its just a matter of my taste to add string manipulation, as i understand it better, but i see the reason for them to be added

Of course, it's better to do what you understand, but in this case - better to try understand middleware `matchers` instead of additional logic inside middleware. 

Remember, that NextJS middleware - is a thing that runs on every request. **More logic on every request - so they will be slower.** Do we want that? Probably not)

Instead of additional logic, you can use `matcher` that was designed for those cases by NextJS devs to skip middleware invocation. It's the fastest (by performance) possible approach, so don't be afraid to use something new, it's worth it! 🚀

**Review by Iarynovskyi — APPROVED** [review]

File: middleware.ts [hunk 1]
```diff
@@ -7,6 +7,6 @@ export const middleware = (request: NextRequest) => {
 
 export const config = {
     matcher: [
-        '/((?!api|_next/static|_next/image|favicon.ico).*)'
+        '/((?!api|_next/static|_next/image|favicon.ico|.*\\.[^/]+$).*)'
```
Comment (ShadowOfTheSpace) [inline middleware.ts:10]: Nice modification with `.*\\.[^/]+$`.
Is it really work for `route.with.dot/example`?

**Review by ShadowOfTheSpace — APPROVED** [review]

File: middleware.ts (hunk 1 above)
Comment (yur4uwe) [reply middleware.ts:10]: just checked, and doesn't work as expected, investigating this issue

Comment (yur4uwe) [reply middleware.ts:10]: False alarm, server wasn't working

regex works as expected (lets middleware process it) with this path

Comment (ShadowOfTheSpace) [reply middleware.ts:10]: So it skips static files, but runs for the routes (even with a dot in the path), right?

Comment (yur4uwe) [reply middleware.ts:10]: exactly

though it wont work for something like /example.smth.anyth and /example.smth.

**Review by oleg191006 — APPROVED** [review]

**Review by danikua — APPROVED** [review]
